# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming', '0002_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesearch',
            name='game_found',
            field=models.BooleanField(default=False),
        ),
    ]
