# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 00:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gaming', '0003_gamesearch_game_found'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gaming.Server')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gaming.DiscordUser')),
            ],
            options={
                'verbose_name_plural': 'Server Users',
                'verbose_name': 'Server User',
            },
        ),
    ]
