# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-24 05:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gaming', '0008_auto_20161123_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('message_token', models.CharField(blank=True, max_length=50, null=True)),
                ('message', models.TextField(default='')),
                ('email', models.BooleanField(default=False)),
                ('subject', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('body', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(choices=[('ATG', 'Add to a gaame')], max_length=4000)),
                ('task_info', models.CharField(blank=True, max_length=4000, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expire_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('cancelled', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gaming.Server')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gaming.DiscordUser')),
            ],
        ),
    ]
