# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-24 06:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gaming', '0009_log_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gaming.Channel'),
        ),
        migrations.AddField(
            model_name='task',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gaming.Game'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.CharField(choices=[('ATG', 'Add to a game')], max_length=4000),
        ),
    ]
