# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-27 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming', '0010_auto_20161123_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='discorduser',
            name='bot',
            field=models.BooleanField(default=False),
        ),
    ]
