# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-27 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gaming', '0011_discorduser_bot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('content', models.CharField(max_length=4000)),
                ('message_id', models.CharField(max_length=4000)),
            ],
        ),
        migrations.AlterField(
            model_name='channel',
            name='channel_id',
            field=models.CharField(max_length=4000, unique=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='name',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='user_id',
            field=models.CharField(max_length=4000, unique=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='log',
            name='body',
            field=models.CharField(blank=True, default=None, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='subject',
            field=models.CharField(blank=True, default=None, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_id',
            field=models.CharField(max_length=4000, unique=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='name',
            field=models.CharField(blank=True, default='', max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='server_id',
            field=models.CharField(max_length=4000, unique=True),
        ),
        migrations.AddField(
            model_name='message',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gaming.Channel'),
        ),
        migrations.AddField(
            model_name='message',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gaming.Server'),
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gaming.DiscordUser'),
        ),
    ]
