# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-27 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming', '0014_auto_20161127_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='warning_sent',
            field=models.BooleanField(default=False),
        ),
    ]
