# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-04 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming', '0017_channeluser'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='icon',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
    ]
