# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-04 08:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gaming', '0018_server_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gaming.DiscordUser'),
            preserve_default=False,
        ),
    ]
