# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-26 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming', '0024_auto_20161225_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='attachment',
        ),
        migrations.AddField(
            model_name='attachment',
            name='attachment_id',
            field=models.CharField(default=1, max_length=4000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attachment',
            name='url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='attachments',
            field=models.ManyToManyField(to='gaming.Attachment'),
        ),
    ]
