# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-31 00:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gaming', '0025_auto_20161226_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_by', to='gaming.DiscordUser')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gaming.Server')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gaming.DiscordUser')),
            ],
            options={
                'verbose_name_plural': 'Quotes',
                'verbose_name': 'Quote',
            },
        ),
    ]
