# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-31 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming', '0026_quote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='user',
        ),
        migrations.AddField(
            model_name='quote',
            name='users',
            field=models.ManyToManyField(to='gaming.DiscordUser'),
        ),
    ]
