# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-14 18:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gaming', '0028_auto_20161230_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordUserHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('field_modified', models.CharField(choices=[('user_id', 'user_id'), ('name', 'name'), ('bot', 'bot'), ('avatar_url', 'avatar_url')], max_length=4000)),
                ('old_value', models.CharField(max_length=4000)),
                ('new_value', models.CharField(max_length=4000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gaming.DiscordUser')),
            ],
            options={
                'verbose_name': 'Discord User History',
                'verbose_name_plural': 'Discord User Histories',
            },
        ),
    ]
