# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 21:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Channels',
                'verbose_name': 'Channel',
            },
        ),
        migrations.CreateModel(
            name='DiscordUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Discord Users',
                'verbose_name': 'Discord User',
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Servers',
                'verbose_name': 'Server',
            },
        ),
        migrations.CreateModel(
            name='ServerUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='privatechannel.Server')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='privatechannel.DiscordUser')),
            ],
            options={
                'verbose_name_plural': 'Server Users',
                'verbose_name': 'Server User',
            },
        ),
        migrations.AddField(
            model_name='channel',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='privatechannel.Server'),
        ),
    ]
