language: python

python:
  - 3.5.2

services: postgresql

env:
  - DJANGO=1.10.1

before_install:
  - export DJANGO_SETTINGS_MODULE=web.settings
  - export PYTHONPATH=$HOME/builds/bsquidwrd/squid-bot
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt
  - pip install django==$DJANGO --quiet
  - pip install psycopg2 --quiet

before_script:
  - cp web/environment_example.py web/environment.py
  - psql -c "CREATE DATABASE travisci;" -U postgres

script:
  - python manage.py migrate --noinput

notifications:
  email:
    on_success: change
    on_failure: always
