#   A basic travis.yml boilerplate for Django projects
#
#   The set-up assumes a postgreSQL database.
#
#   Replace the following variables in the code:
# * your_project_settings
# * your_github_username
# * your_repo

language: python

python:
  - 3.5.1

services: postgresql

env:
  - DJANGO=1.10.1

before_install:
  - export DJANGO_SETTINGS_MODULE=web.settings
  - export PYTHONPATH=$HOME/builds/bsquidwrd/squid-bot
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt
  - pip install django==$DJANGO --quiet
  - pip install psycopg2 --quiet

before_script:
  - psql -c "CREATE DATABASE squidbot;" -U postgres

script:
  - python manage.py migrate --noinput
